[book]
authors = ["lzzsG"]
language = "zh"
multilingual = true
src = "src"
title = "MIT6.175 Labs Instruction"

[output.html]
default-theme = "black"
mathjax-support = true
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/mit6.175-labs-instruction"
git-repository-icon = "fa-github"
