[book]
authors = ["lzzsG"]
language = "en"
multilingual = true
src = "src"
title = "mit6.175-labs-instruction"

[output.html]
default-theme = "black"
mathjax-support = true
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/mit6.175-labs-instruction"
git-repository-icon = "fa-github"

[output.html.redirect]
"/" = "https://lzzs.fun/mit6.175-labs-instruction/zh/MIT6.175.html"
